name: hitung
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  flutter_bloc: ^8.1.3
  flutter_native_splash: ^2.3.9
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  in_app_update: ^4.2.2
  intl: ^0.19.0
  json_annotation: ^4.8.1
  m_widget:
    git:
      url: https://github.com/BlastTea/MWidget.git
      ref: 30a2156d944afd6eb3c75274e4b8b7f9dd9884d8
  pod_player: ^0.2.1
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  # google_mobile_ads: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-Medium.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.otf

